# Generated by Django 4.0.6 on 2022-07-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('close', models.DecimalField(decimal_places=2, max_digits=5)),
                ('high', models.DecimalField(decimal_places=2, max_digits=5)),
                ('low', models.DecimalField(decimal_places=2, max_digits=5)),
                ('open', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.BigIntegerField()),
                ('instrument', models.TextField(max_length=255)),
            ],
        ),
    ]
